[discovery]
gitignore = true

[discovery.roblox]
require = "ReplicatedStorage.packages.lutest"
roots = ["tests/roblox"]

[roblox]
rojo_project = "dev.project.json"
universe_id = 10235501704
place_id = 95525691623663
