[package]
name = "ernisto/defnet"
version = "0.1.0-alpha.3"
license = "MIT"
description = "A simple network definition library."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "lib"]
